#!/usr/bin/env bash
# Palisades-Labs Claude Code harness bootstrap.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/Palisades-Labs/claude-harness-installer/main/bootstrap.sh \
#     | bash -s -- <org>/<repo>
#
# Examples:
#   bash -s -- Palisades-Labs/insidescale-claude-harness
#   bash -s -- insidescale-org/claude-harness
#
# What this does (all additive / idempotent):
#   1. Installs prerequisites: jq, gh, git, rsync, node, npm (via Homebrew on macOS or apt/dnf/yum on Linux).
#   2. Installs Claude Code CLI: `npm i -g @anthropic-ai/claude-code`.
#   3. Ensures you are authenticated with `gh auth login`.
#   4. Appends `export GITHUB_TOKEN=$(gh auth token)` to your shell rc (once).
#   4b. Prompts for a Tavily API key and appends `export TAVILY_API_KEY=...` to your shell rc (once).
#   5. Merges the client marketplace + enabled plugins into ~/.claude/settings.json
#      without touching any unrelated keys.
#
# Does NOT: overwrite existing Claude settings, touch other marketplaces, or install
# anything system-wide beyond what's listed above.

set -euo pipefail

log() { printf "\033[1;34m[bootstrap]\033[0m %s\n" "$*"; }
err() { printf "\033[1;31m[error]\033[0m %s\n" "$*" >&2; }

CLIENT_REPO="${1:-}"
if [[ -z "$CLIENT_REPO" || "$CLIENT_REPO" != */* ]]; then
  err "Usage: bootstrap.sh <org>/<repo>  (e.g. Palisades-Labs/insidescale-claude-harness)"
  exit 1
fi

REPO_NAME="${CLIENT_REPO##*/}"
# Strip '-claude-harness' suffix if present; else use the repo name verbatim.
# This must match the marketplace 'name' field generated by /onboard-client.
MARKETPLACE_NAME="${REPO_NAME%-claude-harness}"

log "Client repo:       $CLIENT_REPO"
log "Marketplace name:  $MARKETPLACE_NAME"

# When piped via `curl | bash`, bash reads this script FROM stdin. Replacing
# stdin with /dev/tty (`exec < /dev/tty`) breaks that — bash stops reading the
# remainder of the script and starts waiting for terminal input instead.
#
# Instead, put /dev/tty on fd 3 so interactive commands below can read from it
# via `<&3` while bash's stdin stays pointed at the pipe.
if [[ -r /dev/tty ]]; then
  exec 3</dev/tty
else
  # No TTY available (rare: CI, cron) — fall back to current stdin.
  exec 3<&0
fi

OS="$(uname -s)"

# -----------------------------------------------------------------------------
# 1) Install prerequisites (jq, gh, node+npm)
# -----------------------------------------------------------------------------
ensure_homebrew() {
  if ! command -v brew &>/dev/null; then
    log "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # Add brew to PATH for this shell (Apple Silicon and Intel paths)
    if [[ -x /opt/homebrew/bin/brew ]]; then
      eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [[ -x /usr/local/bin/brew ]]; then
      eval "$(/usr/local/bin/brew shellenv)"
    fi
  fi
}

install_pkg_macos() {
  ensure_homebrew
  brew install "$1"
}

install_pkg_linux() {
  if command -v apt-get &>/dev/null; then
    sudo apt-get update -qq
    sudo apt-get install -y "$1"
  elif command -v dnf &>/dev/null; then
    sudo dnf install -y "$1"
  elif command -v yum &>/dev/null; then
    sudo yum install -y "$1"
  else
    err "Unsupported Linux distro: no apt/dnf/yum found"
    exit 1
  fi
}

install_pkg() {
  case "$OS" in
    Darwin) install_pkg_macos "$1" ;;
    Linux)  install_pkg_linux  "$1" ;;
    *) err "Unsupported OS: $OS"; exit 1 ;;
  esac
}

ensure_tool() {
  local bin="$1" pkg_darwin="$2" pkg_linux="$3"
  if command -v "$bin" &>/dev/null; then
    log "[ok] $bin present"
  else
    log "Installing $bin..."
    if [[ "$OS" == "Darwin" ]]; then install_pkg "$pkg_darwin"
    else install_pkg "$pkg_linux"; fi
  fi
}

ensure_tool jq    jq   jq
ensure_tool gh    gh   gh
ensure_tool git   git  git
ensure_tool rsync rsync rsync
ensure_tool node  node nodejs
ensure_tool npm   node npm

# -----------------------------------------------------------------------------
# 2) Install Claude Code CLI
# -----------------------------------------------------------------------------
if command -v claude &>/dev/null; then
  log "[ok] claude present ($(claude --version 2>/dev/null || echo unknown))"
else
  log "Installing Claude Code CLI (npm i -g @anthropic-ai/claude-code)..."
  npm install -g @anthropic-ai/claude-code
fi

# -----------------------------------------------------------------------------
# 3) Ensure gh auth
# -----------------------------------------------------------------------------
if gh auth status &>/dev/null; then
  log "[ok] gh already authenticated"
else
  log "Launching 'gh auth login'. Recommended: github.com -> HTTPS -> Login with a web browser."
  gh auth login <&3
fi

# -----------------------------------------------------------------------------
# 4) Ensure GITHUB_TOKEN export in shell rc (additive, idempotent via marker)
# -----------------------------------------------------------------------------
case "$(basename "${SHELL:-}")" in
  zsh)  RC_FILE="$HOME/.zshrc" ;;
  bash) RC_FILE="$HOME/.bashrc" ;;
  *)    RC_FILE="$( [[ "$OS" == "Darwin" ]] && echo "$HOME/.zshrc" || echo "$HOME/.bashrc" )" ;;
esac
touch "$RC_FILE"

MARKER="# Palisades-Labs claude-harness-installer: GITHUB_TOKEN"
if grep -Fq "$MARKER" "$RC_FILE"; then
  log "[ok] GITHUB_TOKEN export already present in $RC_FILE"
else
  log "Adding GITHUB_TOKEN export to $RC_FILE"
  {
    printf '\n%s\n' "$MARKER"
    printf 'export GITHUB_TOKEN=$(gh auth token 2>/dev/null || true)\n'
  } >> "$RC_FILE"
fi

# -----------------------------------------------------------------------------
# 4b) Ensure TAVILY_API_KEY export in shell rc (additive, idempotent via marker)
# -----------------------------------------------------------------------------
# Tavily MCP is bundled with the base plugin. Prompt once; write the export
# alongside GITHUB_TOKEN. Leave unset if the user declines — Tavily tools will
# fail with a clear error until the env var is populated.
TAVILY_MARKER="# Palisades-Labs claude-harness-installer: TAVILY_API_KEY"
if grep -Fq "$TAVILY_MARKER" "$RC_FILE"; then
  log "[ok] TAVILY_API_KEY export already present in $RC_FILE"
else
  printf "Enter your Tavily API key (get one at https://tavily.com, press Enter to skip): "
  read -r TAVILY_KEY <&3
  if [[ -n "$TAVILY_KEY" ]]; then
    log "Adding TAVILY_API_KEY export to $RC_FILE"
    {
      printf '\n%s\n' "$TAVILY_MARKER"
      printf 'export TAVILY_API_KEY=%q\n' "$TAVILY_KEY"
    } >> "$RC_FILE"
  else
    log "[warn] Skipped TAVILY_API_KEY. Tavily tools will fail until you set it."
    log "        Add this line to $RC_FILE later: export TAVILY_API_KEY=<your-key>"
  fi
fi

# -----------------------------------------------------------------------------
# 5) Additive merge into ~/.claude/settings.json
# -----------------------------------------------------------------------------
SETTINGS_DIR="$HOME/.claude"
SETTINGS="$SETTINGS_DIR/settings.json"
mkdir -p "$SETTINGS_DIR"

if [[ ! -f "$SETTINGS" ]]; then
  echo '{}' > "$SETTINGS"
  log "Created empty $SETTINGS"
fi

if ! jq empty "$SETTINGS" 2>/dev/null; then
  err "$SETTINGS is not valid JSON. Refusing to modify. Fix it first, then re-run."
  exit 1
fi

TMP="$(mktemp)"
jq --arg mp "$MARKETPLACE_NAME" --arg repo "$CLIENT_REPO" '
    .extraKnownMarketplaces //= {}
  | .extraKnownMarketplaces[$mp] = { source: { source: "github", repo: $repo } }
  | .enabledPlugins //= {}
  | .enabledPlugins["base@\($mp)"] = true
  | .enabledPlugins["\($mp)@\($mp)"] = true
' "$SETTINGS" > "$TMP"

# Only replace if content changed, to keep the idempotent-rerun signal clean.
if cmp -s "$TMP" "$SETTINGS"; then
  rm -f "$TMP"
  log "[ok] settings.json already has the right marketplace + plugins"
else
  mv "$TMP" "$SETTINGS"
  log "[ok] settings.json updated (additive merge)"
fi

# -----------------------------------------------------------------------------
# 6) Done
# -----------------------------------------------------------------------------
echo ""
log "Bootstrap complete."
echo ""
echo "Next steps:"
echo "  1. Open a NEW terminal so GITHUB_TOKEN gets picked up."
echo "  2. Run: claude"
echo "  3. Inside Claude, check: /plugin list"
echo ""
